// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -source=cache.go -destination=../../mocks/mock_caching.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	fmt "fmt"
	reflect "reflect"
	time "time"

	types "github.com/lifenetwork-ai/go-backend-template/infrastructures/caching/types"
	gomock "go.uber.org/mock/gomock"
)

// MockCacheClient is a mock of CacheClient interface.
type MockCacheClient struct {
	ctrl     *gomock.Controller
	recorder *MockCacheClientMockRecorder
	isgomock struct{}
}

// MockCacheClientMockRecorder is the mock recorder for MockCacheClient.
type MockCacheClientMockRecorder struct {
	mock *MockCacheClient
}

// NewMockCacheClient creates a new mock instance.
func NewMockCacheClient(ctrl *gomock.Controller) *MockCacheClient {
	mock := &MockCacheClient{ctrl: ctrl}
	mock.recorder = &MockCacheClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheClient) EXPECT() *MockCacheClientMockRecorder {
	return m.recorder
}

// Decr mocks base method.
func (m *MockCacheClient) Decr(ctx context.Context, key string, delta int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decr", ctx, key, delta)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decr indicates an expected call of Decr.
func (mr *MockCacheClientMockRecorder) Decr(ctx, key, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decr", reflect.TypeOf((*MockCacheClient)(nil).Decr), ctx, key, delta)
}

// Del mocks base method.
func (m *MockCacheClient) Del(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockCacheClientMockRecorder) Del(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockCacheClient)(nil).Del), ctx, key)
}

// ExpireNX mocks base method.
func (m *MockCacheClient) ExpireNX(ctx context.Context, key string, expiration time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireNX", ctx, key, expiration)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpireNX indicates an expected call of ExpireNX.
func (mr *MockCacheClientMockRecorder) ExpireNX(ctx, key, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireNX", reflect.TypeOf((*MockCacheClient)(nil).ExpireNX), ctx, key, expiration)
}

// Get mocks base method.
func (m *MockCacheClient) Get(ctx context.Context, key string, dest any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockCacheClientMockRecorder) Get(ctx, key, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacheClient)(nil).Get), ctx, key, dest)
}

// Incr mocks base method.
func (m *MockCacheClient) Incr(ctx context.Context, key string, delta int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Incr", ctx, key, delta)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Incr indicates an expected call of Incr.
func (mr *MockCacheClientMockRecorder) Incr(ctx, key, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Incr", reflect.TypeOf((*MockCacheClient)(nil).Incr), ctx, key, delta)
}

// Set mocks base method.
func (m *MockCacheClient) Set(ctx context.Context, key string, value any, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheClientMockRecorder) Set(ctx, key, value, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheClient)(nil).Set), ctx, key, value, expiration)
}

// SetMany mocks base method.
func (m *MockCacheClient) SetMany(ctx context.Context, items []types.ClientBatchItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMany", ctx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMany indicates an expected call of SetMany.
func (mr *MockCacheClientMockRecorder) SetMany(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMany", reflect.TypeOf((*MockCacheClient)(nil).SetMany), ctx, items)
}

// TTL mocks base method.
func (m *MockCacheClient) TTL(ctx context.Context, key string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TTL", ctx, key)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TTL indicates an expected call of TTL.
func (mr *MockCacheClientMockRecorder) TTL(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TTL", reflect.TypeOf((*MockCacheClient)(nil).TTL), ctx, key)
}

// MockCacheRepository is a mock of CacheRepository interface.
type MockCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockCacheRepositoryMockRecorder is the mock recorder for MockCacheRepository.
type MockCacheRepositoryMockRecorder struct {
	mock *MockCacheRepository
}

// NewMockCacheRepository creates a new mock instance.
func NewMockCacheRepository(ctrl *gomock.Controller) *MockCacheRepository {
	mock := &MockCacheRepository{ctrl: ctrl}
	mock.recorder = &MockCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepository) EXPECT() *MockCacheRepositoryMockRecorder {
	return m.recorder
}

// DecrementItem mocks base method.
func (m *MockCacheRepository) DecrementItem(key fmt.Stringer, delta int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementItem", key, delta)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementItem indicates an expected call of DecrementItem.
func (mr *MockCacheRepositoryMockRecorder) DecrementItem(key, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementItem", reflect.TypeOf((*MockCacheRepository)(nil).DecrementItem), key, delta)
}

// ExpireNX mocks base method.
func (m *MockCacheRepository) ExpireNX(key fmt.Stringer, expire time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireNX", key, expire)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpireNX indicates an expected call of ExpireNX.
func (mr *MockCacheRepositoryMockRecorder) ExpireNX(key, expire any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireNX", reflect.TypeOf((*MockCacheRepository)(nil).ExpireNX), key, expire)
}

// IncrementItem mocks base method.
func (m *MockCacheRepository) IncrementItem(key fmt.Stringer, delta int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementItem", key, delta)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementItem indicates an expected call of IncrementItem.
func (mr *MockCacheRepositoryMockRecorder) IncrementItem(key, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementItem", reflect.TypeOf((*MockCacheRepository)(nil).IncrementItem), key, delta)
}

// RemoveItem mocks base method.
func (m *MockCacheRepository) RemoveItem(key fmt.Stringer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockCacheRepositoryMockRecorder) RemoveItem(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockCacheRepository)(nil).RemoveItem), key)
}

// RetrieveItem mocks base method.
func (m *MockCacheRepository) RetrieveItem(key fmt.Stringer, val any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveItem", key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetrieveItem indicates an expected call of RetrieveItem.
func (mr *MockCacheRepositoryMockRecorder) RetrieveItem(key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveItem", reflect.TypeOf((*MockCacheRepository)(nil).RetrieveItem), key, val)
}

// SaveItem mocks base method.
func (m *MockCacheRepository) SaveItem(key fmt.Stringer, val any, expire time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveItem", key, val, expire)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveItem indicates an expected call of SaveItem.
func (mr *MockCacheRepositoryMockRecorder) SaveItem(key, val, expire any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveItem", reflect.TypeOf((*MockCacheRepository)(nil).SaveItem), key, val, expire)
}

// SaveItems mocks base method.
func (m *MockCacheRepository) SaveItems(items []types.RepoBatchItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveItems", items)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveItems indicates an expected call of SaveItems.
func (mr *MockCacheRepositoryMockRecorder) SaveItems(items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveItems", reflect.TypeOf((*MockCacheRepository)(nil).SaveItems), items)
}

// TTL mocks base method.
func (m *MockCacheRepository) TTL(key fmt.Stringer) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TTL", key)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TTL indicates an expected call of TTL.
func (mr *MockCacheRepositoryMockRecorder) TTL(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TTL", reflect.TypeOf((*MockCacheRepository)(nil).TTL), key)
}
