// Code generated by MockGen. DO NOT EDIT.
// Source: rate_limiter.go
//
// Generated by this command:
//
//	mockgen -source=rate_limiter.go -package=mocks -destination=../../mocks/mock_rate_limiter.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRateLimiter is a mock of RateLimiter interface.
type MockRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterMockRecorder
	isgomock struct{}
}

// MockRateLimiterMockRecorder is the mock recorder for MockRateLimiter.
type MockRateLimiterMockRecorder struct {
	mock *MockRateLimiter
}

// NewMockRateLimiter creates a new mock instance.
func NewMockRateLimiter(ctrl *gomock.Controller) *MockRateLimiter {
	mock := &MockRateLimiter{ctrl: ctrl}
	mock.recorder = &MockRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiter) EXPECT() *MockRateLimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockRateLimiter) Allow(key string, limit int, window time.Duration) (bool, int, time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", key, limit, window)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(time.Duration)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Allow indicates an expected call of Allow.
func (mr *MockRateLimiterMockRecorder) Allow(key, limit, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockRateLimiter)(nil).Allow), key, limit, window)
}

// ResetAttempts mocks base method.
func (m *MockRateLimiter) ResetAttempts(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetAttempts", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetAttempts indicates an expected call of ResetAttempts.
func (mr *MockRateLimiterMockRecorder) ResetAttempts(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetAttempts", reflect.TypeOf((*MockRateLimiter)(nil).ResetAttempts), key)
}
