// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_manager.go
//
// Generated by this command:
//
//	mockgen -source=transaction_manager.go -destination=../../mocks/mock_transaction_manager.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repositories "github.com/lifenetwork-ai/life-cloud-agent-node/internal/domain/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockTxRepositories is a mock of TxRepositories interface.
type MockTxRepositories struct {
	ctrl     *gomock.Controller
	recorder *MockTxRepositoriesMockRecorder
	isgomock struct{}
}

// MockTxRepositoriesMockRecorder is the mock recorder for MockTxRepositories.
type MockTxRepositoriesMockRecorder struct {
	mock *MockTxRepositories
}

// NewMockTxRepositories creates a new mock instance.
func NewMockTxRepositories(ctrl *gomock.Controller) *MockTxRepositories {
	mock := &MockTxRepositories{ctrl: ctrl}
	mock.recorder = &MockTxRepositoriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxRepositories) EXPECT() *MockTxRepositoriesMockRecorder {
	return m.recorder
}

// Examples mocks base method.
func (m *MockTxRepositories) Examples() repositories.ExampleRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Examples")
	ret0, _ := ret[0].(repositories.ExampleRepository)
	return ret0
}

// Examples indicates an expected call of Examples.
func (mr *MockTxRepositoriesMockRecorder) Examples() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Examples", reflect.TypeOf((*MockTxRepositories)(nil).Examples))
}

// MockTransactionManager is a mock of TransactionManager interface.
type MockTransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionManagerMockRecorder
	isgomock struct{}
}

// MockTransactionManagerMockRecorder is the mock recorder for MockTransactionManager.
type MockTransactionManagerMockRecorder struct {
	mock *MockTransactionManager
}

// NewMockTransactionManager creates a new mock instance.
func NewMockTransactionManager(ctrl *gomock.Controller) *MockTransactionManager {
	mock := &MockTransactionManager{ctrl: ctrl}
	mock.recorder = &MockTransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionManager) EXPECT() *MockTransactionManagerMockRecorder {
	return m.recorder
}

// WithinTx mocks base method.
func (m *MockTransactionManager) WithinTx(ctx context.Context, fn func(repositories.TxRepositories) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTx indicates an expected call of WithinTx.
func (mr *MockTransactionManagerMockRecorder) WithinTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTx", reflect.TypeOf((*MockTransactionManager)(nil).WithinTx), ctx, fn)
}
