// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lifenetwork-ai/life-cloud-agent-node/internal/domain/repositories (interfaces: PatientRegistryRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_patient_registry_repository.go -package=mocks . PatientRegistryRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entities "github.com/lifenetwork-ai/life-cloud-agent-node/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockPatientRegistryRepository is a mock of PatientRegistryRepository interface.
type MockPatientRegistryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPatientRegistryRepositoryMockRecorder
	isgomock struct{}
}

// MockPatientRegistryRepositoryMockRecorder is the mock recorder for MockPatientRegistryRepository.
type MockPatientRegistryRepositoryMockRecorder struct {
	mock *MockPatientRegistryRepository
}

// NewMockPatientRegistryRepository creates a new mock instance.
func NewMockPatientRegistryRepository(ctrl *gomock.Controller) *MockPatientRegistryRepository {
	mock := &MockPatientRegistryRepository{ctrl: ctrl}
	mock.recorder = &MockPatientRegistryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientRegistryRepository) EXPECT() *MockPatientRegistryRepositoryMockRecorder {
	return m.recorder
}

// CountLabObservations mocks base method.
func (m *MockPatientRegistryRepository) CountLabObservations(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLabObservations", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLabObservations indicates an expected call of CountLabObservations.
func (mr *MockPatientRegistryRepositoryMockRecorder) CountLabObservations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLabObservations", reflect.TypeOf((*MockPatientRegistryRepository)(nil).CountLabObservations), ctx)
}

// CountPatients mocks base method.
func (m *MockPatientRegistryRepository) CountPatients(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPatients", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPatients indicates an expected call of CountPatients.
func (mr *MockPatientRegistryRepositoryMockRecorder) CountPatients(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPatients", reflect.TypeOf((*MockPatientRegistryRepository)(nil).CountPatients), ctx)
}

// CountSpecimens mocks base method.
func (m *MockPatientRegistryRepository) CountSpecimens(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSpecimens", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSpecimens indicates an expected call of CountSpecimens.
func (mr *MockPatientRegistryRepositoryMockRecorder) CountSpecimens(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSpecimens", reflect.TypeOf((*MockPatientRegistryRepository)(nil).CountSpecimens), ctx)
}

// GetOrCreatePatient mocks base method.
func (m *MockPatientRegistryRepository) GetOrCreatePatient(ctx context.Context, externalPatientID string) (*entities.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreatePatient", ctx, externalPatientID)
	ret0, _ := ret[0].(*entities.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreatePatient indicates an expected call of GetOrCreatePatient.
func (mr *MockPatientRegistryRepositoryMockRecorder) GetOrCreatePatient(ctx, externalPatientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreatePatient", reflect.TypeOf((*MockPatientRegistryRepository)(nil).GetOrCreatePatient), ctx, externalPatientID)
}

// GetPatientByExternalID mocks base method.
func (m *MockPatientRegistryRepository) GetPatientByExternalID(ctx context.Context, externalPatientID string) (*entities.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatientByExternalID", ctx, externalPatientID)
	ret0, _ := ret[0].(*entities.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatientByExternalID indicates an expected call of GetPatientByExternalID.
func (mr *MockPatientRegistryRepositoryMockRecorder) GetPatientByExternalID(ctx, externalPatientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatientByExternalID", reflect.TypeOf((*MockPatientRegistryRepository)(nil).GetPatientByExternalID), ctx, externalPatientID)
}

// GetPatientByID mocks base method.
func (m *MockPatientRegistryRepository) GetPatientByID(ctx context.Context, id uuid.UUID) (*entities.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatientByID", ctx, id)
	ret0, _ := ret[0].(*entities.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatientByID indicates an expected call of GetPatientByID.
func (mr *MockPatientRegistryRepositoryMockRecorder) GetPatientByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatientByID", reflect.TypeOf((*MockPatientRegistryRepository)(nil).GetPatientByID), ctx, id)
}

// GetSpecimenByID mocks base method.
func (m *MockPatientRegistryRepository) GetSpecimenByID(ctx context.Context, id uuid.UUID) (*entities.Specimen, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpecimenByID", ctx, id)
	ret0, _ := ret[0].(*entities.Specimen)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpecimenByID indicates an expected call of GetSpecimenByID.
func (mr *MockPatientRegistryRepositoryMockRecorder) GetSpecimenByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpecimenByID", reflect.TypeOf((*MockPatientRegistryRepository)(nil).GetSpecimenByID), ctx, id)
}

// ListObservationsBySpecimenID mocks base method.
func (m *MockPatientRegistryRepository) ListObservationsBySpecimenID(ctx context.Context, specimenID uuid.UUID) ([]*entities.LabObservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObservationsBySpecimenID", ctx, specimenID)
	ret0, _ := ret[0].([]*entities.LabObservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObservationsBySpecimenID indicates an expected call of ListObservationsBySpecimenID.
func (mr *MockPatientRegistryRepositoryMockRecorder) ListObservationsBySpecimenID(ctx, specimenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObservationsBySpecimenID", reflect.TypeOf((*MockPatientRegistryRepository)(nil).ListObservationsBySpecimenID), ctx, specimenID)
}

// SaveSpecimen mocks base method.
func (m *MockPatientRegistryRepository) SaveSpecimen(ctx context.Context, specimen *entities.Specimen, observations []*entities.LabObservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSpecimen", ctx, specimen, observations)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSpecimen indicates an expected call of SaveSpecimen.
func (mr *MockPatientRegistryRepositoryMockRecorder) SaveSpecimen(ctx, specimen, observations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSpecimen", reflect.TypeOf((*MockPatientRegistryRepository)(nil).SaveSpecimen), ctx, specimen, observations)
}
