// Code generated by MockGen. DO NOT EDIT.
// Source: job_progress.go
//
// Generated by this command:
//
//	mockgen -source=job_progress.go -destination=../../mocks/mock_job_progress_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/lifenetwork-ai/life-cloud-agent-node/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockJobProgressRepository is a mock of JobProgressRepository interface.
type MockJobProgressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobProgressRepositoryMockRecorder
	isgomock struct{}
}

// MockJobProgressRepositoryMockRecorder is the mock recorder for MockJobProgressRepository.
type MockJobProgressRepositoryMockRecorder struct {
	mock *MockJobProgressRepository
}

// NewMockJobProgressRepository creates a new mock instance.
func NewMockJobProgressRepository(ctrl *gomock.Controller) *MockJobProgressRepository {
	mock := &MockJobProgressRepository{ctrl: ctrl}
	mock.recorder = &MockJobProgressRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobProgressRepository) EXPECT() *MockJobProgressRepositoryMockRecorder {
	return m.recorder
}

// DeleteFinishedBefore mocks base method.
func (m *MockJobProgressRepository) DeleteFinishedBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFinishedBefore", ctx, cutoff)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFinishedBefore indicates an expected call of DeleteFinishedBefore.
func (mr *MockJobProgressRepositoryMockRecorder) DeleteFinishedBefore(ctx, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFinishedBefore", reflect.TypeOf((*MockJobProgressRepository)(nil).DeleteFinishedBefore), ctx, cutoff)
}

// Get mocks base method.
func (m *MockJobProgressRepository) Get(ctx context.Context, jobID string) (*entities.JobProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, jobID)
	ret0, _ := ret[0].(*entities.JobProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockJobProgressRepositoryMockRecorder) Get(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockJobProgressRepository)(nil).Get), ctx, jobID)
}

// Save mocks base method.
func (m *MockJobProgressRepository) Save(ctx context.Context, progress *entities.JobProgress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockJobProgressRepositoryMockRecorder) Save(ctx, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockJobProgressRepository)(nil).Save), ctx, progress)
}
