// Code generated by MockGen. DO NOT EDIT.
// Source: example.go
//
// Generated by this command:
//
//	mockgen -source=example.go -destination=../../../mocks/mock_example_ucase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	contracts "github.com/lifenetwork-ai/go-backend-template/internal/domain/contracts"
	types "github.com/lifenetwork-ai/go-backend-template/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockExampleUseCase is a mock of ExampleUseCase interface.
type MockExampleUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockExampleUseCaseMockRecorder
	isgomock struct{}
}

// MockExampleUseCaseMockRecorder is the mock recorder for MockExampleUseCase.
type MockExampleUseCaseMockRecorder struct {
	mock *MockExampleUseCase
}

// NewMockExampleUseCase creates a new mock instance.
func NewMockExampleUseCase(ctrl *gomock.Controller) *MockExampleUseCase {
	mock := &MockExampleUseCase{ctrl: ctrl}
	mock.recorder = &MockExampleUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExampleUseCase) EXPECT() *MockExampleUseCaseMockRecorder {
	return m.recorder
}

// CreateExample mocks base method.
func (m *MockExampleUseCase) CreateExample(ctx context.Context, input contracts.CreateExampleInput) (*contracts.ExampleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExample", ctx, input)
	ret0, _ := ret[0].(*contracts.ExampleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExample indicates an expected call of CreateExample.
func (mr *MockExampleUseCaseMockRecorder) CreateExample(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExample", reflect.TypeOf((*MockExampleUseCase)(nil).CreateExample), ctx, input)
}

// DeleteExample mocks base method.
func (m *MockExampleUseCase) DeleteExample(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExample", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExample indicates an expected call of DeleteExample.
func (mr *MockExampleUseCaseMockRecorder) DeleteExample(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExample", reflect.TypeOf((*MockExampleUseCase)(nil).DeleteExample), ctx, id)
}

// GetExample mocks base method.
func (m *MockExampleUseCase) GetExample(ctx context.Context, id uuid.UUID) (*contracts.ExampleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExample", ctx, id)
	ret0, _ := ret[0].(*contracts.ExampleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExample indicates an expected call of GetExample.
func (mr *MockExampleUseCaseMockRecorder) GetExample(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExample", reflect.TypeOf((*MockExampleUseCase)(nil).GetExample), ctx, id)
}

// ListExamples mocks base method.
func (m *MockExampleUseCase) ListExamples(ctx context.Context, input contracts.ListExamplesInput) (*types.PaginatedResponse[*contracts.ExampleOutput], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExamples", ctx, input)
	ret0, _ := ret[0].(*types.PaginatedResponse[*contracts.ExampleOutput])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExamples indicates an expected call of ListExamples.
func (mr *MockExampleUseCaseMockRecorder) ListExamples(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExamples", reflect.TypeOf((*MockExampleUseCase)(nil).ListExamples), ctx, input)
}

// UpdateExample mocks base method.
func (m *MockExampleUseCase) UpdateExample(ctx context.Context, input contracts.UpdateExampleInput) (*contracts.ExampleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExample", ctx, input)
	ret0, _ := ret[0].(*contracts.ExampleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateExample indicates an expected call of UpdateExample.
func (mr *MockExampleUseCaseMockRecorder) UpdateExample(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExample", reflect.TypeOf((*MockExampleUseCase)(nil).UpdateExample), ctx, input)
}
