// Code generated by MockGen. DO NOT EDIT.
// Source: hospital_governance.go
//
// Generated by this command:
//
//	mockgen -source=hospital_governance.go -destination=../../mocks/mock_hospital_governance_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/lifenetwork-ai/life-cloud-agent-node/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockHospitalGovernanceRepository is a mock of HospitalGovernanceRepository interface.
type MockHospitalGovernanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHospitalGovernanceRepositoryMockRecorder
	isgomock struct{}
}

// MockHospitalGovernanceRepositoryMockRecorder is the mock recorder for MockHospitalGovernanceRepository.
type MockHospitalGovernanceRepositoryMockRecorder struct {
	mock *MockHospitalGovernanceRepository
}

// NewMockHospitalGovernanceRepository creates a new mock instance.
func NewMockHospitalGovernanceRepository(ctrl *gomock.Controller) *MockHospitalGovernanceRepository {
	mock := &MockHospitalGovernanceRepository{ctrl: ctrl}
	mock.recorder = &MockHospitalGovernanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHospitalGovernanceRepository) EXPECT() *MockHospitalGovernanceRepositoryMockRecorder {
	return m.recorder
}

// AppendAudit mocks base method.
func (m *MockHospitalGovernanceRepository) AppendAudit(ctx context.Context, event entities.HospitalGovernanceAuditRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendAudit", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendAudit indicates an expected call of AppendAudit.
func (mr *MockHospitalGovernanceRepositoryMockRecorder) AppendAudit(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendAudit", reflect.TypeOf((*MockHospitalGovernanceRepository)(nil).AppendAudit), ctx, event)
}

// Get mocks base method.
func (m *MockHospitalGovernanceRepository) Get(ctx context.Context, nodeID string) (*entities.HospitalGovernance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, nodeID)
	ret0, _ := ret[0].(*entities.HospitalGovernance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHospitalGovernanceRepositoryMockRecorder) Get(ctx, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHospitalGovernanceRepository)(nil).Get), ctx, nodeID)
}

// GetCommand mocks base method.
func (m *MockHospitalGovernanceRepository) GetCommand(ctx context.Context, nodeID, actor, key string) (*entities.HospitalGovernanceCommandRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommand", ctx, nodeID, actor, key)
	ret0, _ := ret[0].(*entities.HospitalGovernanceCommandRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommand indicates an expected call of GetCommand.
func (mr *MockHospitalGovernanceRepositoryMockRecorder) GetCommand(ctx, nodeID, actor, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommand", reflect.TypeOf((*MockHospitalGovernanceRepository)(nil).GetCommand), ctx, nodeID, actor, key)
}

// Lock mocks base method.
func (m *MockHospitalGovernanceRepository) Lock(ctx context.Context, nodeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx, nodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lock indicates an expected call of Lock.
func (mr *MockHospitalGovernanceRepositoryMockRecorder) Lock(ctx, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockHospitalGovernanceRepository)(nil).Lock), ctx, nodeID)
}

// Save mocks base method.
func (m *MockHospitalGovernanceRepository) Save(ctx context.Context, state *entities.HospitalGovernance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockHospitalGovernanceRepositoryMockRecorder) Save(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockHospitalGovernanceRepository)(nil).Save), ctx, state)
}

// SaveCommand mocks base method.
func (m *MockHospitalGovernanceRepository) SaveCommand(ctx context.Context, command entities.HospitalGovernanceCommandRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCommand", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCommand indicates an expected call of SaveCommand.
func (mr *MockHospitalGovernanceRepositoryMockRecorder) SaveCommand(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCommand", reflect.TypeOf((*MockHospitalGovernanceRepository)(nil).SaveCommand), ctx, command)
}
