// Code generated by MockGen. DO NOT EDIT.
// Source: cohort_count.go
//
// Generated by this command:
//
//	mockgen -source=cohort_count.go -destination=../../../mocks/mock_cohort_count_ucase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/lifenetwork-ai/life-cloud-agent-node/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockCohortCountUseCase is a mock of CohortCountUseCase interface.
type MockCohortCountUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCohortCountUseCaseMockRecorder
	isgomock struct{}
}

// MockCohortCountUseCaseMockRecorder is the mock recorder for MockCohortCountUseCase.
type MockCohortCountUseCaseMockRecorder struct {
	mock *MockCohortCountUseCase
}

// NewMockCohortCountUseCase creates a new mock instance.
func NewMockCohortCountUseCase(ctrl *gomock.Controller) *MockCohortCountUseCase {
	mock := &MockCohortCountUseCase{ctrl: ctrl}
	mock.recorder = &MockCohortCountUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCohortCountUseCase) EXPECT() *MockCohortCountUseCaseMockRecorder {
	return m.recorder
}

// CountMatchingCohort mocks base method.
func (m *MockCohortCountUseCase) CountMatchingCohort(ctx context.Context, jobID string, criteria types.CohortCriteria) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMatchingCohort", ctx, jobID, criteria)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMatchingCohort indicates an expected call of CountMatchingCohort.
func (mr *MockCohortCountUseCaseMockRecorder) CountMatchingCohort(ctx, jobID, criteria any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMatchingCohort", reflect.TypeOf((*MockCohortCountUseCase)(nil).CountMatchingCohort), ctx, jobID, criteria)
}
