// Code generated by MockGen. DO NOT EDIT.
// Source: enabled_query_field.go
//
// Generated by this command:
//
//	mockgen -source=enabled_query_field.go -destination=../../../mocks/mock_enabled_query_field_ucase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	contracts "github.com/lifenetwork-ai/life-cloud-agent-node/internal/domain/contracts"
	gomock "go.uber.org/mock/gomock"
)

// MockEnabledQueryFieldUseCase is a mock of EnabledQueryFieldUseCase interface.
type MockEnabledQueryFieldUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockEnabledQueryFieldUseCaseMockRecorder
	isgomock struct{}
}

// MockEnabledQueryFieldUseCaseMockRecorder is the mock recorder for MockEnabledQueryFieldUseCase.
type MockEnabledQueryFieldUseCaseMockRecorder struct {
	mock *MockEnabledQueryFieldUseCase
}

// NewMockEnabledQueryFieldUseCase creates a new mock instance.
func NewMockEnabledQueryFieldUseCase(ctrl *gomock.Controller) *MockEnabledQueryFieldUseCase {
	mock := &MockEnabledQueryFieldUseCase{ctrl: ctrl}
	mock.recorder = &MockEnabledQueryFieldUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnabledQueryFieldUseCase) EXPECT() *MockEnabledQueryFieldUseCaseMockRecorder {
	return m.recorder
}

// ListQueryFields mocks base method.
func (m *MockEnabledQueryFieldUseCase) ListQueryFields(ctx context.Context) ([]*contracts.EnabledQueryFieldOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQueryFields", ctx)
	ret0, _ := ret[0].([]*contracts.EnabledQueryFieldOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQueryFields indicates an expected call of ListQueryFields.
func (mr *MockEnabledQueryFieldUseCaseMockRecorder) ListQueryFields(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQueryFields", reflect.TypeOf((*MockEnabledQueryFieldUseCase)(nil).ListQueryFields), ctx)
}

// UpdateQueryField mocks base method.
func (m *MockEnabledQueryFieldUseCase) UpdateQueryField(ctx context.Context, input contracts.UpdateEnabledQueryFieldInput) (*contracts.EnabledQueryFieldOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQueryField", ctx, input)
	ret0, _ := ret[0].(*contracts.EnabledQueryFieldOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQueryField indicates an expected call of UpdateQueryField.
func (mr *MockEnabledQueryFieldUseCaseMockRecorder) UpdateQueryField(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQueryField", reflect.TypeOf((*MockEnabledQueryFieldUseCase)(nil).UpdateQueryField), ctx, input)
}
