// Code generated by MockGen. DO NOT EDIT.
// Source: hospital_governance.go
//
// Generated by this command:
//
//	mockgen -source=hospital_governance.go -destination=../../../mocks/mock_hospital_governance_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/lifenetwork-ai/life-cloud-agent-node/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockHospitalGovernanceUseCase is a mock of HospitalGovernanceUseCase interface.
type MockHospitalGovernanceUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockHospitalGovernanceUseCaseMockRecorder
	isgomock struct{}
}

// MockHospitalGovernanceUseCaseMockRecorder is the mock recorder for MockHospitalGovernanceUseCase.
type MockHospitalGovernanceUseCaseMockRecorder struct {
	mock *MockHospitalGovernanceUseCase
}

// NewMockHospitalGovernanceUseCase creates a new mock instance.
func NewMockHospitalGovernanceUseCase(ctrl *gomock.Controller) *MockHospitalGovernanceUseCase {
	mock := &MockHospitalGovernanceUseCase{ctrl: ctrl}
	mock.recorder = &MockHospitalGovernanceUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHospitalGovernanceUseCase) EXPECT() *MockHospitalGovernanceUseCaseMockRecorder {
	return m.recorder
}

// Acknowledge mocks base method.
func (m *MockHospitalGovernanceUseCase) Acknowledge(arg0 context.Context, arg1 string, arg2, arg3 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acknowledge", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Acknowledge indicates an expected call of Acknowledge.
func (mr *MockHospitalGovernanceUseCaseMockRecorder) Acknowledge(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acknowledge", reflect.TypeOf((*MockHospitalGovernanceUseCase)(nil).Acknowledge), arg0, arg1, arg2, arg3)
}

// ApplySnapshot mocks base method.
func (m *MockHospitalGovernanceUseCase) ApplySnapshot(arg0 context.Context, arg1 entities.HospitalSnapshot) (*entities.HospitalGovernanceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplySnapshot", arg0, arg1)
	ret0, _ := ret[0].(*entities.HospitalGovernanceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplySnapshot indicates an expected call of ApplySnapshot.
func (mr *MockHospitalGovernanceUseCaseMockRecorder) ApplySnapshot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySnapshot", reflect.TypeOf((*MockHospitalGovernanceUseCase)(nil).ApplySnapshot), arg0, arg1)
}

// ChangeAcceptance mocks base method.
func (m *MockHospitalGovernanceUseCase) ChangeAcceptance(arg0 context.Context, arg1, arg2 string, arg3 entities.HospitalAcceptanceChange) (*entities.HospitalGovernanceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeAcceptance", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*entities.HospitalGovernanceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeAcceptance indicates an expected call of ChangeAcceptance.
func (mr *MockHospitalGovernanceUseCaseMockRecorder) ChangeAcceptance(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeAcceptance", reflect.TypeOf((*MockHospitalGovernanceUseCase)(nil).ChangeAcceptance), arg0, arg1, arg2, arg3)
}

// ChangeAvailability mocks base method.
func (m *MockHospitalGovernanceUseCase) ChangeAvailability(arg0 context.Context, arg1, arg2 string, arg3 bool, arg4 int64) (*entities.HospitalGovernanceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeAvailability", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*entities.HospitalGovernanceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeAvailability indicates an expected call of ChangeAvailability.
func (mr *MockHospitalGovernanceUseCaseMockRecorder) ChangeAvailability(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeAvailability", reflect.TypeOf((*MockHospitalGovernanceUseCase)(nil).ChangeAvailability), arg0, arg1, arg2, arg3, arg4)
}

// FenceConnection mocks base method.
func (m *MockHospitalGovernanceUseCase) FenceConnection(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FenceConnection", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// FenceConnection indicates an expected call of FenceConnection.
func (mr *MockHospitalGovernanceUseCaseMockRecorder) FenceConnection(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FenceConnection", reflect.TypeOf((*MockHospitalGovernanceUseCase)(nil).FenceConnection), arg0)
}

// Invalidate mocks base method.
func (m *MockHospitalGovernanceUseCase) Invalidate(arg0 context.Context, arg1 entities.HospitalInvalidationCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockHospitalGovernanceUseCaseMockRecorder) Invalidate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockHospitalGovernanceUseCase)(nil).Invalidate), arg0, arg1)
}

// Read mocks base method.
func (m *MockHospitalGovernanceUseCase) Read(arg0 context.Context) (*entities.HospitalGovernanceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(*entities.HospitalGovernanceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockHospitalGovernanceUseCaseMockRecorder) Read(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockHospitalGovernanceUseCase)(nil).Read), arg0)
}

// UpdatePolicy mocks base method.
func (m *MockHospitalGovernanceUseCase) UpdatePolicy(arg0 context.Context, arg1, arg2 string, arg3 entities.HospitalPolicyRecord, arg4 int64) (*entities.HospitalGovernanceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePolicy", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*entities.HospitalGovernanceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePolicy indicates an expected call of UpdatePolicy.
func (mr *MockHospitalGovernanceUseCaseMockRecorder) UpdatePolicy(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePolicy", reflect.TypeOf((*MockHospitalGovernanceUseCase)(nil).UpdatePolicy), arg0, arg1, arg2, arg3, arg4)
}
