// Code generated by MockGen. DO NOT EDIT.
// Source: enabled_query_field.go
//
// Generated by this command:
//
//	mockgen -source=enabled_query_field.go -destination=../../mocks/mock_enabled_query_field_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/lifenetwork-ai/life-cloud-agent-node/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockEnabledQueryFieldRepository is a mock of EnabledQueryFieldRepository interface.
type MockEnabledQueryFieldRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEnabledQueryFieldRepositoryMockRecorder
	isgomock struct{}
}

// MockEnabledQueryFieldRepositoryMockRecorder is the mock recorder for MockEnabledQueryFieldRepository.
type MockEnabledQueryFieldRepositoryMockRecorder struct {
	mock *MockEnabledQueryFieldRepository
}

// NewMockEnabledQueryFieldRepository creates a new mock instance.
func NewMockEnabledQueryFieldRepository(ctrl *gomock.Controller) *MockEnabledQueryFieldRepository {
	mock := &MockEnabledQueryFieldRepository{ctrl: ctrl}
	mock.recorder = &MockEnabledQueryFieldRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnabledQueryFieldRepository) EXPECT() *MockEnabledQueryFieldRepositoryMockRecorder {
	return m.recorder
}

// GetByFieldCode mocks base method.
func (m *MockEnabledQueryFieldRepository) GetByFieldCode(ctx context.Context, fieldCode string) (*entities.EnabledQueryField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFieldCode", ctx, fieldCode)
	ret0, _ := ret[0].(*entities.EnabledQueryField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFieldCode indicates an expected call of GetByFieldCode.
func (mr *MockEnabledQueryFieldRepositoryMockRecorder) GetByFieldCode(ctx, fieldCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFieldCode", reflect.TypeOf((*MockEnabledQueryFieldRepository)(nil).GetByFieldCode), ctx, fieldCode)
}

// ListAll mocks base method.
func (m *MockEnabledQueryFieldRepository) ListAll(ctx context.Context) ([]*entities.EnabledQueryField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]*entities.EnabledQueryField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockEnabledQueryFieldRepositoryMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockEnabledQueryFieldRepository)(nil).ListAll), ctx)
}

// Upsert mocks base method.
func (m *MockEnabledQueryFieldRepository) Upsert(ctx context.Context, entity *entities.EnabledQueryField) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockEnabledQueryFieldRepositoryMockRecorder) Upsert(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockEnabledQueryFieldRepository)(nil).Upsert), ctx, entity)
}
