// Code generated by MockGen. DO NOT EDIT.
// Source: governed_hospital_job.go
//
// Generated by this command:
//
//	mockgen -source=governed_hospital_job.go -destination=../../../mocks/mock_governed_hospital_job_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/lifenetwork-ai/life-cloud-agent-node/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockGovernedHospitalJobUseCase is a mock of GovernedHospitalJobUseCase interface.
type MockGovernedHospitalJobUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGovernedHospitalJobUseCaseMockRecorder
	isgomock struct{}
}

// MockGovernedHospitalJobUseCaseMockRecorder is the mock recorder for MockGovernedHospitalJobUseCase.
type MockGovernedHospitalJobUseCaseMockRecorder struct {
	mock *MockGovernedHospitalJobUseCase
}

// NewMockGovernedHospitalJobUseCase creates a new mock instance.
func NewMockGovernedHospitalJobUseCase(ctrl *gomock.Controller) *MockGovernedHospitalJobUseCase {
	mock := &MockGovernedHospitalJobUseCase{ctrl: ctrl}
	mock.recorder = &MockGovernedHospitalJobUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGovernedHospitalJobUseCase) EXPECT() *MockGovernedHospitalJobUseCaseMockRecorder {
	return m.recorder
}

// AcknowledgeStage mocks base method.
func (m *MockGovernedHospitalJobUseCase) AcknowledgeStage(arg0 context.Context, arg1 entities.GovernedHospitalStageAck) (*entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcknowledgeStage", arg0, arg1)
	ret0, _ := ret[0].(*entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcknowledgeStage indicates an expected call of AcknowledgeStage.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) AcknowledgeStage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcknowledgeStage", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).AcknowledgeStage), arg0, arg1)
}

// Approve mocks base method.
func (m *MockGovernedHospitalJobUseCase) Approve(arg0 context.Context, arg1, arg2 string, arg3 int64, arg4 string) (*entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Approve indicates an expected call of Approve.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) Approve(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).Approve), arg0, arg1, arg2, arg3, arg4)
}

// Begin mocks base method.
func (m *MockGovernedHospitalJobUseCase) Begin(arg0 context.Context, arg1 entities.GovernedHospitalTask) (*entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", arg0, arg1)
	ret0, _ := ret[0].(*entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) Begin(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).Begin), arg0, arg1)
}

// Decline mocks base method.
func (m *MockGovernedHospitalJobUseCase) Decline(arg0 context.Context, arg1, arg2 string, arg3 int64, arg4 string) (*entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decline", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decline indicates an expected call of Decline.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) Decline(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decline", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).Decline), arg0, arg1, arg2, arg3, arg4)
}

// Deny mocks base method.
func (m *MockGovernedHospitalJobUseCase) Deny(arg0 context.Context, arg1 entities.GovernedHospitalDenial) (*entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deny", arg0, arg1)
	ret0, _ := ret[0].(*entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deny indicates an expected call of Deny.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) Deny(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deny", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).Deny), arg0, arg1)
}

// ExpireApproval mocks base method.
func (m *MockGovernedHospitalJobUseCase) ExpireApproval(arg0 context.Context, arg1 string) (*entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireApproval", arg0, arg1)
	ret0, _ := ret[0].(*entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpireApproval indicates an expected call of ExpireApproval.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) ExpireApproval(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireApproval", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).ExpireApproval), arg0, arg1)
}

// Intent mocks base method.
func (m *MockGovernedHospitalJobUseCase) Intent(arg0 context.Context, arg1, arg2 string) (*entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Intent", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Intent indicates an expected call of Intent.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) Intent(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Intent", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).Intent), arg0, arg1, arg2)
}

// ListApprovals mocks base method.
func (m *MockGovernedHospitalJobUseCase) ListApprovals(arg0 context.Context, arg1, arg2 int) ([]entities.GovernedHospitalJobRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApprovals", arg0, arg1, arg2)
	ret0, _ := ret[0].([]entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListApprovals indicates an expected call of ListApprovals.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) ListApprovals(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApprovals", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).ListApprovals), arg0, arg1, arg2)
}

// ListEvents mocks base method.
func (m *MockGovernedHospitalJobUseCase) ListEvents(arg0 context.Context, arg1, arg2 int) ([]entities.GovernedHospitalOutboundEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", arg0, arg1, arg2)
	ret0, _ := ret[0].([]entities.GovernedHospitalOutboundEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) ListEvents(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).ListEvents), arg0, arg1, arg2)
}

// Prepare mocks base method.
func (m *MockGovernedHospitalJobUseCase) Prepare(arg0 context.Context, arg1, arg2 string, arg3 uint64) (*entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prepare indicates an expected call of Prepare.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) Prepare(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).Prepare), arg0, arg1, arg2, arg3)
}

// Read mocks base method.
func (m *MockGovernedHospitalJobUseCase) Read(arg0 context.Context, arg1 string) (*entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(*entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) Read(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).Read), arg0, arg1)
}

// Receive mocks base method.
func (m *MockGovernedHospitalJobUseCase) Receive(arg0 context.Context, arg1 entities.GovernedHospitalReceipt) (*entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive", arg0, arg1)
	ret0, _ := ret[0].(*entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Receive indicates an expected call of Receive.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) Receive(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).Receive), arg0, arg1)
}

// ResumableManual mocks base method.
func (m *MockGovernedHospitalJobUseCase) ResumableManual(arg0 context.Context, arg1 string, arg2 int) ([]entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumableManual", arg0, arg1, arg2)
	ret0, _ := ret[0].([]entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumableManual indicates an expected call of ResumableManual.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) ResumableManual(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumableManual", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).ResumableManual), arg0, arg1, arg2)
}

// Send mocks base method.
func (m *MockGovernedHospitalJobUseCase) Send(arg0 context.Context, arg1 string, arg2 entities.GovernedHospitalGrant) (*entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) Send(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).Send), arg0, arg1, arg2)
}

// Terminate mocks base method.
func (m *MockGovernedHospitalJobUseCase) Terminate(arg0 context.Context, arg1, arg2, arg3, arg4 string) (*entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Terminate", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Terminate indicates an expected call of Terminate.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) Terminate(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Terminate", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).Terminate), arg0, arg1, arg2, arg3, arg4)
}

// Unconfirmed mocks base method.
func (m *MockGovernedHospitalJobUseCase) Unconfirmed(arg0 context.Context, arg1 string, arg2 int) ([]entities.GovernedHospitalOutboundEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unconfirmed", arg0, arg1, arg2)
	ret0, _ := ret[0].([]entities.GovernedHospitalOutboundEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unconfirmed indicates an expected call of Unconfirmed.
func (mr *MockGovernedHospitalJobUseCaseMockRecorder) Unconfirmed(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unconfirmed", reflect.TypeOf((*MockGovernedHospitalJobUseCase)(nil).Unconfirmed), arg0, arg1, arg2)
}
