// Code generated by MockGen. DO NOT EDIT.
// Source: governed_hospital_job.go
//
// Generated by this command:
//
//	mockgen -source=governed_hospital_job.go -destination=../../mocks/mock_governed_hospital_job_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/lifenetwork-ai/life-cloud-agent-node/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockGovernedHospitalJobRepository is a mock of GovernedHospitalJobRepository interface.
type MockGovernedHospitalJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGovernedHospitalJobRepositoryMockRecorder
	isgomock struct{}
}

// MockGovernedHospitalJobRepositoryMockRecorder is the mock recorder for MockGovernedHospitalJobRepository.
type MockGovernedHospitalJobRepositoryMockRecorder struct {
	mock *MockGovernedHospitalJobRepository
}

// NewMockGovernedHospitalJobRepository creates a new mock instance.
func NewMockGovernedHospitalJobRepository(ctrl *gomock.Controller) *MockGovernedHospitalJobRepository {
	mock := &MockGovernedHospitalJobRepository{ctrl: ctrl}
	mock.recorder = &MockGovernedHospitalJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGovernedHospitalJobRepository) EXPECT() *MockGovernedHospitalJobRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGovernedHospitalJobRepository) Get(arg0 context.Context, arg1, arg2 string) (*entities.GovernedHospitalJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entities.GovernedHospitalJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGovernedHospitalJobRepositoryMockRecorder) Get(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGovernedHospitalJobRepository)(nil).Get), arg0, arg1, arg2)
}

// GetEvent mocks base method.
func (m *MockGovernedHospitalJobRepository) GetEvent(arg0 context.Context, arg1, arg2 string) (*entities.GovernedHospitalOutboundEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entities.GovernedHospitalOutboundEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockGovernedHospitalJobRepositoryMockRecorder) GetEvent(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockGovernedHospitalJobRepository)(nil).GetEvent), arg0, arg1, arg2)
}

// ListAwaitingApproval mocks base method.
func (m *MockGovernedHospitalJobRepository) ListAwaitingApproval(arg0 context.Context, arg1 string, arg2, arg3 int) ([]entities.GovernedHospitalJobRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAwaitingApproval", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAwaitingApproval indicates an expected call of ListAwaitingApproval.
func (mr *MockGovernedHospitalJobRepositoryMockRecorder) ListAwaitingApproval(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAwaitingApproval", reflect.TypeOf((*MockGovernedHospitalJobRepository)(nil).ListAwaitingApproval), arg0, arg1, arg2, arg3)
}

// ListEvents mocks base method.
func (m *MockGovernedHospitalJobRepository) ListEvents(arg0 context.Context, arg1 string, arg2, arg3 int) ([]entities.GovernedHospitalOutboundEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]entities.GovernedHospitalOutboundEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockGovernedHospitalJobRepositoryMockRecorder) ListEvents(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockGovernedHospitalJobRepository)(nil).ListEvents), arg0, arg1, arg2, arg3)
}

// ListManualResumable mocks base method.
func (m *MockGovernedHospitalJobRepository) ListManualResumable(arg0 context.Context, arg1, arg2 string, arg3 int) ([]entities.GovernedHospitalJobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListManualResumable", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]entities.GovernedHospitalJobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListManualResumable indicates an expected call of ListManualResumable.
func (mr *MockGovernedHospitalJobRepositoryMockRecorder) ListManualResumable(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListManualResumable", reflect.TypeOf((*MockGovernedHospitalJobRepository)(nil).ListManualResumable), arg0, arg1, arg2, arg3)
}

// ListUnconfirmed mocks base method.
func (m *MockGovernedHospitalJobRepository) ListUnconfirmed(arg0 context.Context, arg1, arg2 string, arg3 int) ([]entities.GovernedHospitalOutboundEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnconfirmed", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]entities.GovernedHospitalOutboundEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnconfirmed indicates an expected call of ListUnconfirmed.
func (mr *MockGovernedHospitalJobRepositoryMockRecorder) ListUnconfirmed(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnconfirmed", reflect.TypeOf((*MockGovernedHospitalJobRepository)(nil).ListUnconfirmed), arg0, arg1, arg2, arg3)
}

// Save mocks base method.
func (m *MockGovernedHospitalJobRepository) Save(arg0 context.Context, arg1 *entities.GovernedHospitalJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGovernedHospitalJobRepositoryMockRecorder) Save(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGovernedHospitalJobRepository)(nil).Save), arg0, arg1)
}

// SaveEvent mocks base method.
func (m *MockGovernedHospitalJobRepository) SaveEvent(arg0 context.Context, arg1 entities.GovernedHospitalOutboundEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEvent indicates an expected call of SaveEvent.
func (mr *MockGovernedHospitalJobRepositoryMockRecorder) SaveEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEvent", reflect.TypeOf((*MockGovernedHospitalJobRepository)(nil).SaveEvent), arg0, arg1)
}
